config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',        to: 'static_pages#help'
  get  '/about',       to: 'static_pages#about'
  get  '/contact',     to: 'static_pages#contact'
  get  '/ministries',  to: 'static_pages#ministries'
  get  '/departments', to: 'static_pages#departments'
  get  '/events',      to: 'static_pages#events'
  get  '/news',        to: 'static_pages#news'
  get  '/blog',        to: 'static_pages#blog'
  get  '/signup',      to: 'members#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def ministries
  end

  def departments
  end

  def events
  end

  def news
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  #Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Pefa Kayole B"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Pefa Kayole B website Designed and built
    by <a href="#">Pefa Kayole B Media Team</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About us",       about_path %></li>
      <li><%= link_to "Contact us",     contact_path %></li>
      <li><%= link_to "Upcomig Events", events_path %></li>
      <li><%= link_to "News",           news_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
<header class="navbar navbar-fixed-top navbar-inverse" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
    <span class="w-100 d-lg-none d-block"><!-- hidden spacer to center brand on mobile --></span>
    <div class="navbar-brand">
    <%= link_to image_tag("pefaLogo.png", :size => "24x24", alt: "Pefa Logo") + "Pefa Kayole B",
            root_path %>
    </div>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav navbar-right">
	   <li><%= link_to "Home",                  root_path, class: "active" %></li>
	   <li class="dropdown">
      <a href="/views/static_pages/about.html.erb" class="dropdown-toggle" data-toggle="dropdown">
                  About <b class="caret"></b>
     <ul class="dropdown-menu">
       <li><%= link_to "Vision",                  about_path %></li>
       <li><%= link_to "Mission",                  about_path %></li>
       <li><%= link_to "Core Values",                  about_path %></li>
       <li><%= link_to "Ministry Purpose",                  about_path %></li>
       <li><%= link_to "Leadership",                  about_path %></li>
     </ul>
     </a> 
  </li>
	<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Ministries
      <b class="caret"></b>
        <ul class="dropdown-menu">
          <li><%= link_to "Childrens Church",                  ministries_path %></li>
          <li><%= link_to "Intercessory",                  ministries_path %></li>
          <li><%= link_to "Chior",                  ministries_path %></li>
          <li><%= link_to "Praise and Worship",                  ministries_path %></li>
          <li><%= link_to "Ushering",                  ministries_path %></li>
          <li><%= link_to "Evangelism",                  ministries_path %></li>
          <li><%= link_to "Hospitality & Followup",                  ministries_path %></li>
        </ul> 
        </a> 
  </li>
	<li class="dropdown">
   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Departments
      <b class="caret"></b>
        <ul class="dropdown-menu">
          <li><%= link_to "Men of Vision",                  departments_path %></li>
          <li><%= link_to "Daughters of Victory",                  departments_path %></li>
          <li><%= link_to "Youths of Destiny",                  departments_path %></li>
          <li><%= link_to "Children Department",                  departments_path %></li>
        </ul>
        </a>   
  </li>
        <li><%= link_to "Help",                  help_path %></li>
        <li><%= link_to "Blog",                  blog_path %></li>
        <li><%= link_to "Log in",                '#' %></li>
      </ul>
    </div>
  </div>
</header>
</div>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
  
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/members/new.html.erb
<% provide(:title, 'Become A Member') %>
<h1>Worship with us</h1>
<p>This will be the page where new members join the church by signing up</p>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="#"><em>Pefa Kayole B</em></a> is a
  <a href="#">Church</a>
  that teaches the word of God
  <a href="#">Church App</a>.
  This is our Web Application.
</p>

app/views/static_pages/blog.html.erb
<% provide(:title, "Blog") %>
<h1>Word From the Pastor's Desk</h1>
<h2>The Gift of The Holy Spirit</h2>
<p>
  <a href="#"><em>Pefa Kayole B</em></a> is a
  <a href="#">Church</a>
  that teaches the word of God
  <a href="#">Church App</a>.
  This is our Web Application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact Pefa Kayole B
  <a href="#">contact page</a>.
</p>

app/views/static_pages/departments.html.erb
<% provide(:title, "Departments") %>
<h1>Departments</h1>
<p>
  <a href="#"><em>Pefa Kayole B</em></a> is a
  <a href="#">Church</a>
  that teaches the word of God
  <a href="#">Church App</a>.
  This is our Web Application.
</p>

app/views/static_pages/events.html.erb
<% provide(:title, "Events") %>
<h1>Upcoming Events</h1>
<p>
  <a href="#"><em>Pefa Kayole B</em></a> is a
  <a href="#">Church</a>
  that teaches the word of God
  <a href="#">Church App</a>.
  This is our Web Application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help on Pefa Kayole B at
  <a href="#">Pefa Kayole B Help</a>.
  To get help on this church app, see the
  <a href="#help"><em>Pefa Kayole B Church App</em> book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container-fluid">
  	<h1>POSITIONED FOR GOD'S GREATNESS</h1>
  	<p class="lead">2 Chronicles 20:17</p>
    <%= link_to "Worship with Us!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>    
</div>

<div class="container about-pefa">
	<div class="row">
		<div class="col-sm-6">
	      <h1 class="text-left">Welcome: The Pefa Kayole B Story</h1>
	       <p>
			Pefa Kayole B was founded in 2004 at Kayole by pastor james ceo.
			the church was initially an independent outfit headed by the - until
			god guided him to join the pefa ministries  which it has been under since.
			There has been tremendous growth since the church was founded fron our humble 
			beginning worshiping in a mabati structre to where we are right now in very 
			strong permanent structure.
		  </p>
	      <%= link_to "Tell Me More?", about_path, class: "btn btn-lg btn-info" %>
		</div>
		<div class="col-sm-6">
		 <%= image_tag("worship.JPG", alt: "rss feed", class: "img-responsive") %>
		</div>

</div>
<br>
<div class="container-fluid bg-1">
	<div class="row">
		<div class="col-sm-6">
			<div class="panel-group" id="accordion">
			    <div class="panel panel-default">
			      <div class="panel-heading">
			        <h4 class="panel-title">
			          <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">Order of Service</a>
			        </h4>
			      </div>
			      <div id="collapse1" class="panel-collapse collapse in">
			        <div class="panel-body">
			        			<p>Youth Service:      7:00am - 8:30am</p>
			        			<p>1st Service:        8:30am - 10:30am</p>
			        			<p>2nd Service:        10:45am - 1: 00pm</p>
			        			<p>Children's Church:  Runs concurrently with the two services</p> 

			        </div>
			      </div>
			    </div>
			    <div class="panel panel-default">
			      <div class="panel-heading">
			        <h4 class="panel-title">
			          <a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Weekely Program</a>
			        </h4>
			      </div>
			      <div id="collapse2" class="panel-collapse collapse">
			        <div class="panel-body">
			        	<p>Chior Practice               Monday & Thursday 5:30 - 7:30pm</p>
			        	<p>Home Fellowships             Tuesday 6pm - 7:30pm</p>
			        	<p>Midweek service:             Wednesday 6pm - 7:30pm</p>
			        	<p>Youth Kesha:                 Every Friday and for the whole church every last friday of the month.</p>
			        	<p>Praise and Worship Practice: Saturday 5pm -6:30pm</p> 
			        </div>
			      </div>
			    </div>
			    <div class="panel panel-default">
			      <div class="panel-heading">
			        <h4 class="panel-title">
			          <a data-toggle="collapse" data-parent="#accordion" href="#collapse3">Monthly Programs</a>
			        </h4>
			      </div>
			      <div id="collapse3" class="panel-collapse collapse">
			        <div class="panel-body">
			        	<p>1st Sunday:      Ministry Meetings</p>
			        	<p>2nd Sunday:      Leaders meeting</p>
			        	<p>3rd Sunday:      Department meetings(Youth, Men and Women)</p>
			        	<p>4th Saturday:    Mission and Evangelism.</p> 
			        </div>
			      </div>
			    </div>
			  </div> 
	    </div>
</div>

app/views/static_pages/ministries.html.erb
<% provide(:title, "Ministries") %>
<h1>Our Ministries</h1>
<p>
  <a href="#"><em>Pefa Kayole B</em></a> is a
  <a href="#">Church</a>
  that teaches the word of God
  <a href="#">Church App</a>.
  This is our Web Application.
</p>

app/views/static_pages/news.html.erb
<% provide(:title, "News") %>
<h1>Announcements</h1>
<p>
  <a href="#"><em></em></a> is a
  <a href="#">Church</a>
  that teaches the word of God
  <a href="#">Church App</a>.
  This is our Web Application.
</p>